# Links on sidebar
menu:
  Lastest: /
  Posts List: /archives/
  Works: /about/
  Categories: /categories/
  Tags: /tags/
  Head First F2E: /categories/前端新手村/
  # Commonweal: /404.html

# Pictures shown on the sidebar
# Use the absolute URL after generating
# avatar: https://avatars1.githubusercontent.com/u/1825852?v=3&s=460
avatar: /assets/head.svg
sidebar_background: #/assets/header.png

# rss: /atom.xml

# Content
excerpt_link: 看看這篇好了...

# Will be shown on the bottom.
## To add new icon, just copy .svg to source/assets/ and add entries below.
media:
  github-alt: https://github.com/dwatow
  facebook-f: https://www.facebook.com/dwatow
  linkedin-in: https://www.linkedin.com/in/chris-wang-604469107

source_han_font: true

# Disqus settings
disqus:
  # 'disabled' | 'all' | 'post'
  enable: post
  # Shortname of your disqus website.
  # See disqus admin
  shortname: dwatow-github

# Miscellaneous
favicon: /favicon.png
